export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS';
export const ADD_TO_BASKET = 'ADD_TO_BASKET';